# Generated by Django 5.2 on 2025-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('experience', models.FloatField()),
                ('packege', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('no_of_jobs', models.IntegerField()),
            ],
        ),
    ]
