# Generated by Django 5.2 on 2025-04-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_mechjobs_itjobs_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itjobs',
            name='resume',
            field=models.FileField(upload_to='files'),
        ),
    ]
