# Generated by Django 5.2 on 2025-04-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_alter_itjobs_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itjobs',
            name='resume',
        ),
    ]
