# Generated by Django 5.2 on 2025-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itjobs',
            name='resume',
            field=models.FileField(default='00', upload_to='files'),
        ),
    ]
